# DSN (Data Source Name) examples
#
# sqlite3:
#   sqlite3://<%= root %>/db/development.sqlite3
# mysql:
#   mysql://user:pass@host/database
# postgres:
#   postgres://user:pass@host/database
# heroku:
#   <%= ENV['DATABASE_URL'] %>
production:
  dsn: mysql://<%= ENV['DB_USER'] %>:<%= ENV['DB_PASSWD'] %>@<%= ENV['DB_HOST'] %>/<%= ENV['DB_NAME'] %>
development:
  dsn: sqlite3://<%= root %>/db/development.sqlite3
test:
  dsn: <%= ENV['DATABASE_URL'] || "sqlite3://#{root}/db/test.sqlite3" %>
